### ISSUE TITLE
XMLHttpRequest - admin-ajax.php?action=job_manager_get_listings error

### ISSUE THREAD

**Issue by hedonehawker** [mikejolley/WP-Job-Manager#471] opened 2015-05-29 00:39 UTC
Hey Mike!

So, please bare with me trough this one since I really tried to find the solution on our side but unfortunately with no luck.

So we used GoDaddy VPS with cPanel till now and now we are moving to new VPS offered by Linode. New VPS with much more processor power and more RAM.

We have transfered a lot of our websites to this new server already and with great results in speed and reliability. Not even one of this websites had any errors except one and that is the only one using WP Job Manager.

All our websites are running with SSL and still XMLHttpRequest error came up for the first time for us.

We have error using configuration that in whole (domain names are changed) is "Mixed Content: The page at 'https://domain1.com/some-category/' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://domain1.com/'. This request has been blocked; the content must be served over HTTPS."

on the other hand if you do website test you get admin-ajax.php?action=job_manager_get_listings error where your plugin wants to use admin-ajax.php.

So we took some steps on our side first:
1. recreating server configuration on new server to be mirror of the one at GoDaddy - No luck
2. deleting all of plugins but WP Job Manager on new server - No luck
3. Making mirror copy on same domain with same database and files - No luck
4. creating test domain with new WP install and WP Job Manager - no luck
5. copying website to test domain on new server and deleting everything byt WP Job Manager plugin - no luck
6. mirror CloudFlare settings on both test and real domain - no luck
7. disabling CloudFlare - no luck
8. doing research on this case - no luck

We have this installation still online, so if you want to you can contact me at branko.nikolic@bayini.com and I'll gladly provide you with access to this installation so you can check it out.

Since this needs to be moved to new server asap I would really appreciate your help with this. unfortunately after spending three days on solving this error, we are no where closer to solution than we were. The only difference is that with install where only your plugin is running, we were able to narrow down the list of things that can be connected to this problem.

**Comment by mikejolley** [comment] 2015-05-29 17:14
Have you viewed the source to see what URL admin-ajax is being returned as? Sounds like SSL by proxy.

**Comment by evertsemeijn** [comment] 2015-05-30 08:51
After enabling SSL on one of our client sites the AJAX job list isn't loading. Might be related.

**Comment by brankonikolic** [comment] 2015-05-30 11:24
@mikejolley - please explain a bit better what and where to check and I'll try to check everything about proxy in our new server and be back with results.
@evertsemeijn - it is I think the same error we are facing. We also run it on SSL. Please keep me in the loop if you'll find a server side solution for it.

**Comment by mikejolley** [comment] 2015-05-30 12:01
The admin-ajax URL will be part of the page source. You did not provide a link to check.

**Comment by brankonikolic** [comment] 2015-05-30 17:57
Hey Mike!

Sorry for not understanding what you ment. Here is the whole query in error: https://coob.me/wp-admin/admin-ajax.php?action=job_manager_get_listings&search_keywords=&search_location=&search_categories%5B%5D=&filter_job_type%5B%5D=freelance&filter_job_type%5B%5D=full-time&filter_job_type%5B%5D=internship&filter_job_type%5B%5D=part-time&filter_job_type%5B%5D=temporary&filter_job_type%5B%5D=&per_page=10&orderby=featured&order=DESC&page=1&show_pagination=true&form_data=search_keywords%3D%26search_location%3D%26search_categories%255B%255D%3D%26use_search_radius%3Don%26search_radius%3D50%26search_lat%3D0%26search_lng%3D0%26search_context%3D0%26filter_job_type%255B%255D%3Dfreelance%26filter_job_type%255B%255D%3Dfull-time%26filter_job_type%255B%255D%3Dinternship%26filter_job_type%255B%255D%3Dpart-time%26filter_job_type%255B%255D%3Dtemporary%26filter_job_type%255B%255D%3D

and here is the other one that is also in error: https://coob.me/wp-admin/admin-ajax.php?action=job_manager_get_listings&search_keywords=&search_location=&search_categories%5B%5D=&filter_job_type%5B%5D=freelance&filter_job_type%5B%5D=full-time&filter_job_type%5B%5D=internship&filter_job_type%5B%5D=part-time&filter_job_type%5B%5D=temporary&filter_job_type%5B%5D=&per_page=10&orderby=featured&order=DESC&page=1&show_pagination=true&form_data=search_keywords%3D%26search_location%3D%26search_categories%255B%255D%3D%26use_search_radius%3Don%26search_radius%3D50%26search_lat%3D0%26search_lng%3D0%26search_context%3D0%26filter_job_type%255B%255D%3Dfreelance%26filter_job_type%255B%255D%3Dfull-time%26filter_job_type%255B%255D%3Dinternship%26filter_job_type%255B%255D%3Dpart-time%26filter_job_type%255B%255D%3Dtemporary%26filter_job_type%255B%255D%3D

you can check this out for yourself here: http://tools.pingdom.com/fpt/#!/evG2n/https://coob.me/listings/

As @evertsemeijn said before, this is only a problem when SSL is enabled. I really think he is facing the same problem as I am.

**Comment by evertsemeijn** [comment] 2015-05-30 18:11
URL looks familiar to what I have seen in the output. Can't switch back at the moment to double-check, otherwise I would have updated this issue. @mikejolley Maybe a optional static job list is an option (as I have suggested before) :-)

**Comment by mikejolley** [comment] 2015-05-30 18:14
I have seen this before actually. The HTTPS error is a red herring; the issue is that the ajax request (you pasted) is being 302 redirected to your homepage.

This can be caused by:

- a security plugin
- website config e.g. htaccess
- something on the server e.g. mod_security not allowing the query string

Other users with this issue have had it fixed by the hosting providers.

**Comment by brankonikolic** [comment] 2015-05-30 18:20
Hey @mikejolley and @evertsemeijn 

let's try to fix this together. So let's see what I'm able to do on my side, just so that other users will have help in the future. 

So suggestions:
1. security plugin is not installed. Nothing but WP, theme and WP Job Manager is on this install
2. Website config e.g. htaccess is configured as classical WP htaccess only. here is what you can find in it:
# BEGIN WordPress
<IfModule mod_rewrite.c>
RewriteEngine On
RewriteBase /
RewriteRule ^index\.php$ - [L]
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule . /index.php [L]
</IfModule>
# END WordPress
So this one shouldn't be a problem.
3. let me check mod_security settings on server.

Problem is that in my case hosting is actually our own VPS so no hosting company is behind to help us out. It did work on GoDaddy's VPS but it does not on Linod, even with same settings on both servers (as described in first post here).

I'll try to check our mod_security settings with one of our guys here. 

@evertsemeijn - can you please check with your hosting provider, so that we can get their answer to this problem?

**Comment by mikejolley** [comment] 2015-05-30 18:22
@brankonikolic I would suggest debugging this with the default WP theme and no other plugins first. Then try to narrow down what is redirecting. Just go to the link directly. A working site should show 'data' and not your homepage.

**Comment by evertsemeijn** [comment] 2015-05-30 18:25
@mikejolley I'll go through the error.log @brankonikolic Hosting myself but not on Apache. You might want to check the implementation of SSL. I assume you added a redirect on port 80.

**Comment by mikejolley** [comment] 2015-05-30 18:29
@evertsemeijn https://coob.me/wp-admin/admin-ajax.php works without the query string. I think its mod_sec

**Comment by brankonikolic** [comment] 2015-05-30 18:30
I believe I was able to get to the problem. You were right, problem is in 950109: Multiple URL Encoding Detected mod_security rule. 

It is part of OWASP rule set - http://go.cpanel.net/modsecurityowasp

If I disable SWASP roules, I'm able to run this website with no problem.

Now we have two options:
1. disable this rule and expose server to attackers
2. wait to see if maybe there is solution on your side to do queries in some other way?

What is your opinion?

**Comment by mikejolley** [comment] 2015-05-30 18:31
@brankonikolic are you on the latest version of the rule set?

**Comment by brankonikolic** [comment] 2015-05-30 18:32
@mikejolley auto update, so I should be. Deleting whole pack and reinstalling. Will report back in a few secs.

**Comment by brankonikolic** [comment] 2015-05-30 19:06
So... @mikejolley OWSAP rule REQUEST-20-PROTOCOL-ENFORCEMENT is the one that redirects your query to main domain instead of giving result. 

I'll look in to how to correct that without turning this rule off, since it is one of those we absolutely need. Can you on the other side pls check if there is any way to do query without amin-ajax?

**Comment by mikejolley** [comment] 2015-05-30 19:14
@brankonikolic Whether we use admin ajax or a custom ajax endpoint, that rule will be triggered either way (if we use a GET request).

**Comment by brankonikolic** [comment] 2015-05-30 19:22
I'm checking around the net to find a solution to this but till now with no luck. And yes, latest version of rule set is on server. So what I'm looking in to now is how to allow this query and still prevent others. But as you already saw, this rule actually cuts off all get requests and from what I'm able to find, this is common problem to quite a lot of developers.

What I suggest is to enable block of GET in htaccess for other GET requests for all websites people are using on their servers. if someone can came up with better solution, I'll gladly take it in to consideration, since my solution is actually allowing human factor (never good idea)... ;)

**Comment by mikejolley** [comment] 2015-05-30 19:27
Maybe it would be good to figure out which data triggered the error from : https://github.com/mikejolley/WP-Job-Manager/blob/master/assets/js/ajax-filters.js#L62-L74

**Comment by hedonehawker** [comment] 2015-05-30 19:34
I think It would. so for the next few hours I'm still going to have this installation up and running. That way you are able to check it out. I would do it for you, but I need to attend a meeting and after that we're gonna disable this rule and put the website on.

Let me enable this rule for you if you think you'll be able to spend a few mins in the next hour.

In any case, we were able to find where error is coming from and how to fix it.

I must thank you @mikejolley for your input and willingness to find a solution and help out!!! Also @evertsemeijn for your input!


PS: love WP Job Manager!!!! ;)

**Closed** 2015-05-30 21:50 UTC
