### ISSUE TITLE
Conditional display of job info based on member level

### ISSUE THREAD

**Issue by fraximus** [mikejolley/WP-Job-Manager#456] opened 2015-05-04 18:06 UTC
Trying to figure out what type of job this is or where the mod would need to be done. 
Here's what I'm trying to do.

I have a membership site where we want to show a list of job postings (as a teaser) to non members. 
Only paid members get the full postings. 

I'm guessing we would have to customize the loop for the WPjobmanager post-type to display only the job data we want to show for each user group.  

Am I on the right track?
Anything built in to WPjobManager that would make this easier?

**Comment by mikejolley** [comment] 2015-05-05 22:44
https://wpjobmanager.com/document/template-overrides/ - override the content template and wrap the content you want hidden with a check. 

https://codex.wordpress.org/Function_Reference/current_user_can

Closing this as its not a bug report :)

**Closed by mikejolley** 2015-05-05 22:44 UTC
