### ISSUE TITLE
Apply button

### ISSUE THREAD

**Issue by cmeurer** [mikejolley/WP-Job-Manager#462] opened 2015-05-14 17:42 UTC
Can the Apply button go directly to email to avoid an additional click, as well as have the Job Title pre-poulated in the Subject line? If so, how?
See: http://advocatestaffing.com/dev/job/enter-director-international-program-esltesol/

**Comment by mikejolley** [comment] 2015-05-14 19:39
Take a look here https://wpjobmanager.com/document/customising-job-application-process/#section-2 Yes its possible.

Closing this issue however - github is for bug reports only.

**Closed by mikejolley** 2015-05-14 19:39 UTC

**Comment by cmeurer** [comment] 2015-05-18 16:07
I realize you closed this and thank you for the link to instructions... however, I used the code provided in your link and it doesn't work (so, maybe it's a bug?) -- http://advocatestaffing.com/dev/job/learning-associate/
The button still opens the text below that asks you to click AGAIN to apply, and now there is an additional "Apply for Job" link below the button that opens a NEW window as well as an email. I just want the button to open an email.... no link below it, no new window opening, no content appearing below the button. Better yet, I'd love for the job name to appear in the subject area (but realize that part isn't a bug, just a request). I'm trying to set this site live today so any help would be very much appreciated!

**Comment by cmeurer** [comment] 2015-05-19 17:57
Can someone please reply to this? Thank you!

**Comment by mikejolley** [comment] 2015-05-19 18:57
Sounds like you changed the wrong file. You have full control over all the template files so you definitely can change what the button does, or if you even have a button at all :)

**Comment by cmeurer** [comment] 2015-05-19 19:04
I changed job-application.php, per the instructions... Isn't that the
correct file? I do like the button, but just want to skip the step of it
opening that stuff that appears below it. Would like it to just open the
email client with the job title pre-filled in the Subject line. I thought
that's what the code from your link above was supposed to do....? This is
the code I used for job-application.php (which is in a job_manager folder
in the theme folder). I don't know how to code php.... Here's the code I
used:

<?php if ( $apply = get_the_job_application_method() ) :
	if ( $apply->type === 'url' ) {
	    $application_href = $apply->url;
	} elseif ( $apply->type === 'email' ) {
	    $application_href = sprintf( 'mailto:%1$s%2$s', $apply->email,
'?subject=' . rawurlencode( $apply->subject )  );
	}
	?>
	<div class="application">
		<a class="application_button button" href="<?php echo
$application_href; ?>"><?php _e( 'Apply for job', 'wp-job-manager' );
?></a>
	</div>
<?php endif; ?>

**Comment by cmeurer** [comment] 2015-05-19 19:18
Actually, I ADDED the new code rather than replace - so that's why it was showing the link and button, sorry! I have that fixed now but this is a BUG -- the link still opens a new window AND the email client. I don't want the user to be taken off the job page when they click to Apply. How can I prevent it from opening that new window?

**Comment by cmeurer** [comment] 2015-05-20 19:39
Are you able to provide a solution to this issue, please?

**Comment by evertsemeijn** [comment] 2015-05-20 19:44
Please only use GitHub to report issues. If you don't know how to make the suggested changes try to find a developer that can fix this for you :)

**Comment by cmeurer** [comment] 2015-05-20 19:46
Sorry, it seems like it a bug to me that it should JUST open up the email client but that it ALSO opens up a blank window for no reason. Is that really how it is supposed to work?!

**Comment by mikejolley** [comment] 2015-05-24 00:50
If you're changing default behaviour its not a bug.. its customisation. Mailto links don't need target="blank" which sounds like you've done.
