### ISSUE TITLE
Search Through 2 taxonomies

### ISSUE THREAD

**Issue by nicschouten** [mikejolley/WP-Job-Manager#449] opened 2015-04-22 13:59 UTC
I want to search through 2 taxonomies within one search textbox: job_listing_category and job_listing_tag

Currently I replacet https://github.com/mikejolley/WP-Job-Manager/blob/master/templates/job-filters.php#L31 with the next code: 

					<?php 
					
					$tags = array( 
					'taxonomy' => 'job_listing_tag', 
					'hierarchical' => 1, 
					'name' => 'search_categories', 
					'selected' => $selected_category, 
					'multiple' => false 
					); 
					
					$cast = array( 
					'taxonomy' => 'job_listing_category', 
					'hierarchical' => 1, 
					'show_option_all' => __( 'Klacht', 'wp-job-manager' ), 
					'name' => 'search_categories', 
					'selected' => $selected_category, 
					'multiple' => false 
					);
					
					$args = asort(array_merge($tags, $cast));					
					
					job_manager_dropdown_categories( $args ); 
					
					?>

As you can see I want to merge 2 taxonomies into 1 array so it can be searched through the [jobs] parameter.

Can you tell me why I am getting just the results of job_listing_category instead of both?

Regards nic

**Comment by mikejolley** [comment] 2015-04-22 22:44
Because the code which handles this field only looks for category. There is no way for it to know which type of taxonomy is being sent through to it. You would need to do more customisation to the code which processes these fields. That gets quite advanced because WordPress needs to know the taxonomy its looking up.

TBH what you're doing doesn't make sense. If the data should be searched as one, use one taxonomy.

I am closing this issue because it's not a bug report (please only use github for core bug reports). Thanks.

**Closed by mikejolley** 2015-04-22 22:44 UTC
